// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs3pl5c2TV0JzVPDXtLPwcehj8KgkO-gw',
    appId: '1:335384254065:web:196c5adb05f165e3c9edd0',
    messagingSenderId: '335384254065',
    projectId: 'dsi2022',
    authDomain: 'dsi2022.firebaseapp.com',
    storageBucket: 'dsi2022.appspot.com',
    measurementId: 'G-9LWV8B3GEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1flzG3WFdiLh7j3VEDKbX-vYj78OjZbs',
    appId: '1:335384254065:android:d2d728d186c5d33ac9edd0',
    messagingSenderId: '335384254065',
    projectId: 'dsi2022',
    storageBucket: 'dsi2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM4iXNZYdtGI07o8UnWIl07EZDRCkzSls',
    appId: '1:335384254065:ios:a0f841d1a6333f82c9edd0',
    messagingSenderId: '335384254065',
    projectId: 'dsi2022',
    storageBucket: 'dsi2022.appspot.com',
    iosClientId: '335384254065-vvd9a0o539fr9qmcupbbhj9dq5ncc5sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupNamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM4iXNZYdtGI07o8UnWIl07EZDRCkzSls',
    appId: '1:335384254065:ios:a0f841d1a6333f82c9edd0',
    messagingSenderId: '335384254065',
    projectId: 'dsi2022',
    storageBucket: 'dsi2022.appspot.com',
    iosClientId: '335384254065-vvd9a0o539fr9qmcupbbhj9dq5ncc5sk.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupNamer',
  );
}
